<h1>nothrow_t</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  struct nothrow_t {};
  extern const nothrow_t nothrow;
}</span></code></pre>
</p>
<h2>概要</h2>
<p><code><span style="color: #000">nothrow_t</span></code>は、<code><span style="color: #000">new</span></code>失敗時に例外を送出させないための型である。
<code><span style="color: #000">nothrow</span></code>は、<code><span style="color: #000">std::nothrow_t</span></code>型の定数であり、<code><span style="color: #000">new</span></code>キーワードに指定するタグとして使用する。</p>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">std::nothrow</span>) int[3];

  // ただし、オブジェクトのコンストラクタが例外を投げる場合は
  // 例外がスローされることに注意
  try
  {
    ThrowObj* obj = new(<span style="color:#ff0000">std::nothrow</span>) ThrowObj();
    delete obj;
  }
  catch (std::logic_error&amp; e)
  {
    // この場合でもnew(<span style="color:#ff0000">std::nothrow</span>)で確保されたメモリは解放されている。
    std::cout &lt;&lt; e.what() &lt;&lt; std::endl;
  }
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;new&gt;

struct ThrowObj
{
  ThrowObj()
  {
    throw std::logic_error("logic_error: ThrowObj::ThrowObj()");
  }
};

int main()
{
  // 長さ3の動的配列を作成する
  // 領域確保に失敗した場合、nullptrが返される
  int* p = new(</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">logic_error: ThrowObj::ThrowObj()
</span></code></pre></p>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/new/nothrow_t.md" target="_blank">編集</a></footer>