<h1>current_exception (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  exception_ptr current_exception() noexcept;
}</span></code></pre>
</p>
<h2>概要</h2>
<p>現在処理中の例外オブジェクトを指す<code><span style="color: #000">exception_ptr</span></code>を取得する。</p>
<h2>戻り値</h2>
<p>現在処理中の例外オブジェクトを指す<code><span style="color: #000">exception_ptr</span></code>を返す。
処理中の例外オブジェクトがない場合は、ヌルを指す<code><span style="color: #000">exception_ptr</span></code>を返す。</p>
<h2>例外</h2>
<p>投げない</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">current_exception</span>(); // 処理中の例外ポインタを取得
  }

  if (ep) {
    std::cout &lt;&lt; "rethrow" &lt;&lt; std::endl;
    std::rethrow_exception(ep); // 再スロー
  }
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;exception&gt;
#include &lt;stdexcept&gt;

int main()
{
  std::exception_ptr ep;

  try {
    throw std::runtime_error("error!");
  }
  catch (...) {
    std::cout &lt;&lt; "catch" &lt;&lt; std::endl;
    ep = std::</span></code></pre>
</p>
<h3>出力例</h3>
<p><pre><code><span style="color: #000">catch
rethrow

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
terminate called after throwing an instance of 'std::runtime_error'
  what():  error!
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.6.1</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a> ??</li>
</ul>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/current_exception.md" target="_blank">編集</a></footer>