<h1>exception</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  class exception;
}</span></code></pre>
</p>
<h2>概要</h2>
<p><code><span style="color: #000">exception</span></code>クラスは、標準ライブラリが提供する全ての例外クラスの基本クラスである。標準ライブラリによって送出される例外オブジェクトのクラスは全て、このクラスから派生する。したがって、標準の例外は全てこのクラスで補足できる。</p>
<h3>メンバ関数</h3>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td><code><span style="color: #000">exception() noexcept;</span></code><br /><code><span style="color: #000">exception(const exception&amp;) noexcept;</span></code></td>
<td>コンストラクタ</td>
</tr>
<tr>
<td><code><span style="color: #000">virtual ~exception();</span></code></td>
<td>デストラクタ</td>
</tr>
<tr>
<td><code><span style="color: #000">exception&amp; operator=(const exception&amp;) noexcept;</span></code></td>
<td>代入演算子</td>
</tr>
<tr>
<td><code><span style="color: #000">virtual const char* what() const noexcept;</span></code></td>
<td>実装定義のエラー内容を取得する</td>
</tr>
</tbody>
</table>
<h3>例</h3>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;iostream&gt;
#include &lt;exception&gt;
#include &lt;stdexcept&gt; // std::runtime_error

int main()
{
  try {
    bool is_error = true;
    if (is_error) { // なんらかのエラーが発生した
      throw std::runtime_error("error!"); // 例外送出
    }
  }
  catch (std::exception&amp; e) {
    // 例外を補足
    // エラー理由を出力する
    std::cout &lt;&lt; e.what() &lt;&lt; std::endl;
  }
}</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">error!
</span></code></pre></p>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/exception.md" target="_blank">編集</a></footer>