<h1>make_exception_ptr (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  template &lt;class E&gt;
  exception_ptr make_exception_ptr(E e) noexcept;
}</span></code></pre>
</p>
<h2>概要</h2>
<p>引数の例外オブジェクトを元に<code><span style="color: #000">exception_ptr</span></code>を生成する。</p>
<h2>効果</h2>
<p><code><span style="color: #000">try {</span></code>
<code><span style="color: #000">throw e;</span></code>
<code><span style="color: #000">} catch(...) {</span></code>
<code><span style="color: #000">return current_exception();</span></code>
<code><span style="color: #000">}</span></code></p>
<h2>戻り値</h2>
<p>例外オブジェクト<code><span style="color: #000">e</span></code>を指す<code><span style="color: #000">exception_ptr</span></code></p>
<h2>例外</h2>
<p>投げない</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">make_exception_ptr</span>(std::runtime_error("error!!!"));

  try {
    std::rethrow_exception(p);
  }
  catch (std::runtime_error&amp; e) {
    std::cout &lt;&lt; e.what() &lt;&lt; std::endl;
  }
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;exception&gt;
#include &lt;stdexcept&gt; // std::runtime_error

int main()
{
  std::exception_ptr p = std::</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">error!!!
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.7.0</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a> ??</li>
</ul>
<h2>実装例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">template &lt;class E&gt;
exception_ptr make_exception_ptr(E e) noexcept
{
  try {
    throw e;
  }
  catch (...) {
    return current_exception();
  }
}</span></code></pre>
</p>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/make_exception_ptr.md" target="_blank">編集</a></footer>