<h1>set_unexpected</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">namespace std {
  typedef void (*unexpected_handler)();
  unexpected_handler set_unexpected (unexpected_handler f) throw();
}</span></code></pre>
</p>
<h2>概要</h2>
<p>例外指定のある関数内で、指定外の例外が発生した時に呼び出される例外ハンドラを設定する。</p>
<h2>戻り値</h2>
<p>元設定されていた例外ハンドラを返す。</p>
<h2>備考</h2>
<p>関数に例外指定が行われている場合に、指定外の例外が発生した場合、この関数で指定したハンドラを呼び出すように設定することが出来る。</p>
<p>また、ここで設定したハンドラは、プログラムから直接呼び出すことも出来る。定義外例外ハンドラでは、「処理を終了する」もしくは、「例外の送出」を行う。</p>
<p>何も送出しない場合は、終了処理が呼び出されプログラムが終了する。送出する場合は、例外発生地点からの送出と同等の扱いとなる。例外発生地点の関数の例外指定が影響するため、例外ハンドラ内で指定外の例外が発生した場合は、<code><span style="color: #000">terminate()</span></code>が呼び出されプログラムが終了する。</p>
<p>例外ハンドラ内には、カレントの例外として、<code><span style="color: #000">bad_exception</span></code>が渡されておりthrowを呼び出すことで、<code><span style="color: #000">bad_exception</span></code>、その他の例外を指定することで別の例外を送出することが出来る。例外ハンドラを設定しない場合、デフォルトでは、終了処理が発生する。</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;stdexcept&gt;
#include &lt;iostream&gt;

void unexpected_handler()
{
    std::cout &lt;&lt; "unexpected exception!" &lt;&lt; std::endl;
    throw;
}

void other_throw() throw( int, std::bad_exception )
{
    throw 1.0;
}

int main()
{
    std::set_unexpected( unexpected_handler );

    try {
        other_throw();
    }
    catch( std::bad_exception ) {
        std::cout &lt;&lt; "bad_exception." &lt;&lt; std::endl;
    }

    return 0;
}</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">unexpected exception!
bad_exception.
</span></code></pre></p>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/exception/set_unexpected.md" target="_blank">編集</a></footer>