<h1>at</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">const_reference at(size_type n) const;
reference at(size_type n);</span></code></pre>
</p>
<h2>概要</h2>
<p>要素アクセス</p>
<h2>戻り値</h2>
<p><code><span style="color: #000">n</span></code>番目の要素への参照を返す。</p>
<h2>計算量</h2>
<p>定数時間</p>
<h2>例外</h2>
<p><code><span style="color: #000">n &gt;= a.size()</span></code>の場合、<a href="http://cpprefjp.github.io/reference/stdexcept.html"><code><span style="color: #000">out_of_range</span></code></a>例外を送出する。</p>
<h2>備考</h2>
<p><code><span style="color: #000">a.at(n)</span></code> は <code><span style="color: #000">*(a.begin() + n)</span></code> と同じ結果になる。<code><span style="color: #000">at()</span></code>の場合はコンテナの要素数に対して境界チェックを行う。</p>
<h2>例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color:#ff0000">at</span>(2);
  std::cout &lt;&lt; x &lt;&lt; std::endl;

  // 範囲外アクセスした場合、例外が投げられる
  try {
    int&amp; y = v.<span style="color:#ff0000">at</span>(3);
  }
  catch (std::out_of_range&amp; ex) {
    std::cout &lt;&lt; "out of range" &lt;&lt; std::endl;
  }
}<span style="color: #000">#include &lt;iostream&gt;
#include &lt;vector&gt;
#include &lt;stdexcept&gt;

int main()
{
  std::vector&lt;int&gt; v = {3, 1, 4};

  // 2番目の要素を参照する
  int&amp; x = v.</span></code></pre>
</p>
<h3>出力</h3>
<p><pre><code><span style="color: #000">4
out of range
</span></code></pre></p>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/vector/at.md" target="_blank">編集</a></footer>