<h1>bad_weak_ptr (C++11)</h1>
<p><pre class="codehilite"><code class="language-cpp"><a href="http://cpprefjp.github.io/reference/exception/exception.html">exception</a>;
}<span style="color: #000">namespace std {
  class bad_weak_ptr : public </span></code></pre>
</p>
<h2>概要</h2>
<p><code><span style="color: #000">bad_weak_ptr</span></code>は、<a href="http://cpprefjp.github.io/reference/memory/weak_ptr.html"><code><span style="color: #000">weak_ptr</span></code></a>オブジェクトから破棄済みの<a href="http://cpprefjp.github.io/reference/memory/shared_ptr.html"><code><span style="color: #000">shared_ptr</span></code></a>オブジェクトを構築しようとした場合に発生する例外クラスである。
破棄済みの<code><span style="color: #000">shared_ptr</span></code>を監視する<code><span style="color: #000">weak_ptr</span></code>オブジェクトから<code><span style="color: #000">weak_ptr::lock()</span></code>メンバ関数で<code><span style="color: #000">shared_ptr</span></code>オブジェクトを構築した場合、すでに<code><span style="color: #000">shared_ptr</span></code>が破棄されていれば、例外を送出することなく空の<code><span style="color: #000">shared_ptr</span></code>が返される。しかし、破棄済みの<code><span style="color: #000">shared_ptr</span></code>を監視する<code><span style="color: #000">weak_ptr</span></code>オブジェクトが<code><span style="color: #000">shared_ptr</span></code>のコンストラクタ引数として渡された場合には、この例外が送出される。</p>
<h3>メンバ関数</h3>
<table border="1" bordercolor="#888" style="border-collapse:collapse">
<thead>
<tr>
<th>名前</th>
<th>説明</th>
<th>対応バージョン</th>
</tr>
</thead>
<tbody>
<tr>
<td><code><span style="color: #000">bad_weak_ptr() noexcept;</span></code><br /><code><span style="color: #000">bad_weak_ptr(const bad_weak_ptr&amp;) noexcept;</span></code></td>
<td>コンストラクタ</td>
<td>C++11</td>
</tr>
<tr>
<td><code><span style="color: #000">virtual ~bad_weak_ptr() = default;</span></code></td>
<td>デストラクタ</td>
<td>C++11</td>
</tr>
<tr>
<td><code><span style="color: #000">bad_weak_ptr&amp; operator=(const bad_weak_ptr&amp;) noexcept;</span></code></td>
<td>代入演算子</td>
<td>C++11</td>
</tr>
<tr>
<td><code><span style="color: #000">virtual const char* what() const noexcept;</span></code></td>
<td>エラー内容を取得する。文字列<code><span style="color: #000">"bad_weak_ptr"</span></code>が返される</td>
<td>C++11</td>
</tr>
</tbody>
</table>
<h3>例</h3>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">#include &lt;memory&gt;
#include &lt;iostream&gt;

int main() {
  auto sp = std::make_shared&lt;int&gt;(42);
  std::weak_ptr&lt;int&gt; wp(sp);

  sp.reset();
  try {
    std::shared_ptr&lt;int&gt; i(wp);
  } catch(std::exception const&amp; e) {
    std::cout &lt;&lt; e.what() &lt;&lt; std::endl;
  }
}</span></code></pre>
</p>
<h3>出力(GCC 4.7での出力。規格上は"bad_weak_ptr"と出力されるのが正しい)</h3>
<p><pre><code><span style="color: #000">std::bad_weak_ptr
</span></code></pre></p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++11</li>
</ul>
<h3>処理系</h3>
<ul>
<li><a href="http://cpprefjp.github.io/implementation.html#clang">Clang</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC</a>: </li>
<li><a href="http://cpprefjp.github.io/implementation.html#gcc">GCC, C++0x mode</a>: 4.4, 4.7.2(<code><span style="color: #000">what()</span></code>が<code><span style="color: #000">"std::bad_weak_ptr"</span></code>を返すので規格違反。バグ報告済み。<a href="http://gcc.gnu.org/bugzilla/show_bug.cgi?id=55847" target="_blank">#55847</a>)</li>
<li><a href="http://cpprefjp.github.io/implementation.html#icc">ICC</a>: ??</li>
<li><a href="http://cpprefjp.github.io/implementation.html#visual_cpp">Visual C++</a>: 9.0 (TR1), 10.0, 11.0, 12.0<ul>
<li>Visual C++ 10.0までは<code><span style="color: #000">what()</span></code>が<code><span style="color: #000">"tr1::bad_weak_ptr"</span></code>を返す。</li>
</ul>
</li>
</ul>
<h3>参照</h3>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/memory/bad_weak_ptr.md" target="_blank">編集</a></footer>