<h1>デストラクタ</h1>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">~basic_filebuf() override;</span></code></pre>
</p>
<h2>概要</h2>
<p>オブジェクトを破棄する。</p>
<h2>効果</h2>
<p><code><span style="color: #000">close()</span></code>を呼び出す。
そこで例外が発生した場合、catchして何も行わない（再送出しない）。</p>
<h2>事後条件</h2>
<h2>実装例</h2>
<p><pre class="codehilite"><code class="language-cpp"><span style="color: #000">~basic_filebuf() override {
  try {
    close();
  } catch (...) {
  }
}</span></code></pre>
</p>
<h3>注意</h3>
<p>このデストラクタ内で呼び出した<code><span style="color: #000">close</span></code>メンバ関数で何か問題が発生した場合、それを検出する方法はない。
<code><span style="color: #000">close</span></code>メンバ関数が成功したことの判定は、特に書き込み目的でファイルを開いている場合、重要である。
なぜなら、<code><span style="color: #000">close</span></code>内部で<code><span style="color: #000">basic_filebuf</span></code>や<code><span style="color: #000">FILE*</span></code>などが保持するバッファからの書き出しがあるため、ここで書き込み処理に失敗する可能性があるためである。
失敗時の処理をきちんと行うためには、デストラクタに頼らず予め<code><span style="color: #000">close</span></code>メンバ関数を呼び出しておくべきである。</p>
<h2>バージョン</h2>
<h3>言語</h3>
<ul>
<li>C++98</li>
</ul>
<h2>参照</h2>
<footer><a href="https://github.com/cpprefjp/site/edit/master/reference/fstream/basic_filebuf/-basic_filebuf.md" target="_blank">編集</a></footer>